// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod runt {
    pub mod verifier {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host_crypto {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn hash(algorithm: &str, data: &[u8]) -> _rt::Vec<u8> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = algorithm;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = data;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "runt:verifier/host-crypto")]
                    unsafe extern "C" {
                        #[link_name = "hash"]
                        fn wit_import3(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2)
                    };
                    let l4 = *ptr2.add(0).cast::<*mut u8>();
                    let l5 = *ptr2
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len6 = l5;
                    let result7 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn verify_signature(
                scheme: &str,
                message: &[u8],
                signature: &[u8],
                public_key: &[u8],
            ) -> bool {
                unsafe {
                    let vec0 = scheme;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = message;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = signature;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let vec3 = public_key;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "runt:verifier/host-crypto")]
                    unsafe extern "C" {
                        #[link_name = "verify-signature"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import4(
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                            ptr2.cast_mut(),
                            len2,
                            ptr3.cast_mut(),
                            len3,
                        )
                    };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn pairing_check(curve: &str, pairs: &[u8]) -> bool {
                unsafe {
                    let vec0 = curve;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = pairs;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "runt:verifier/host-crypto")]
                    unsafe extern "C" {
                        #[link_name = "pairing-check"]
                        fn wit_import2(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1)
                    };
                    _rt::bool_lift(ret as u8)
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host_storage {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_verification_key(
                key_id: &str,
            ) -> Result<_rt::Vec<u8>, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key_id;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "runt:verifier/host-storage")]
                    unsafe extern "C" {
                        #[link_name = "get-verification-key"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result10 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l7 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l8 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len9 = l8;
                                let bytes9 = _rt::Vec::from_raw_parts(
                                    l7.cast(),
                                    len9,
                                    len9,
                                );
                                _rt::string_lift(bytes9)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result10
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_public_params(
                params_id: &str,
            ) -> Result<_rt::Vec<u8>, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = params_id;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "runt:verifier/host-storage")]
                    unsafe extern "C" {
                        #[link_name = "get-public-params"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result10 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l7 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l8 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len9 = l8;
                                let bytes9 = _rt::Vec::from_raw_parts(
                                    l7.cast(),
                                    len9,
                                    len9,
                                );
                                _rt::string_lift(bytes9)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result10
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod runt {
        pub mod verifier {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod verifier {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub enum VerificationStatus {
                    Valid,
                    Invalid(_rt::String),
                    Error(_rt::String),
                }
                impl ::core::fmt::Debug for VerificationStatus {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            VerificationStatus::Valid => {
                                f.debug_tuple("VerificationStatus::Valid").finish()
                            }
                            VerificationStatus::Invalid(e) => {
                                f.debug_tuple("VerificationStatus::Invalid")
                                    .field(e)
                                    .finish()
                            }
                            VerificationStatus::Error(e) => {
                                f.debug_tuple("VerificationStatus::Error").field(e).finish()
                            }
                        }
                    }
                }
                pub type Proof = _rt::Vec<u8>;
                pub type PublicInputs = _rt::Vec<u8>;
                pub type VerificationKey = _rt::Vec<u8>;
                #[derive(Clone)]
                pub struct VerifierMetadata {
                    pub proof_type_id: _rt::String,
                    pub version: _rt::String,
                    pub curve: _rt::String,
                    pub scheme: _rt::String,
                    pub supports_recursion: bool,
                    pub trusted_setup_required: bool,
                    pub max_proof_size: u64,
                    pub description: _rt::String,
                }
                impl ::core::fmt::Debug for VerifierMetadata {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("VerifierMetadata")
                            .field("proof-type-id", &self.proof_type_id)
                            .field("version", &self.version)
                            .field("curve", &self.curve)
                            .field("scheme", &self.scheme)
                            .field("supports-recursion", &self.supports_recursion)
                            .field(
                                "trusted-setup-required",
                                &self.trusted_setup_required,
                            )
                            .field("max-proof-size", &self.max_proof_size)
                            .field("description", &self.description)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_metadata_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::metadata();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let VerifierMetadata {
                        proof_type_id: proof_type_id2,
                        version: version2,
                        curve: curve2,
                        scheme: scheme2,
                        supports_recursion: supports_recursion2,
                        trusted_setup_required: trusted_setup_required2,
                        max_proof_size: max_proof_size2,
                        description: description2,
                    } = result0;
                    let vec3 = (proof_type_id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (version2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = (curve2.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (scheme2.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    *ptr1.add(8 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match supports_recursion2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(1 + 8 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match trusted_setup_required2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>() = _rt::as_i64(max_proof_size2);
                    let vec7 = (description2.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *ptr1
                        .add(16 + 9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len7;
                    *ptr1
                        .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_metadata<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                    let l6 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l6, l7, 1);
                    let l8 = *arg0
                        .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l9 = *arg0
                        .add(16 + 9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l8, l9, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_verify_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let len2 = arg5;
                    let result3 = T::verify(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result3 {
                        VerificationStatus::Valid => {
                            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        VerificationStatus::Invalid(e) => {
                            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        VerificationStatus::Error(e) => {
                            *ptr4.add(0).cast::<u8>() = (2i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    }
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_verify<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        1 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn metadata() -> VerifierMetadata;
                    fn verify(
                        proof: Proof,
                        public_inputs: PublicInputs,
                        verification_key: VerificationKey,
                    ) -> VerificationStatus;
                }
                #[doc(hidden)]
                #[macro_export]
                macro_rules! __export_runt_verifier_verifier_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "runt:verifier/verifier#metadata")] unsafe extern "C" fn
                        export_metadata() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_metadata_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_runt:verifier/verifier#metadata")] unsafe extern "C"
                        fn _post_return_metadata(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_metadata::<$ty > (arg0) } }
                        #[unsafe (export_name = "runt:verifier/verifier#verify")] unsafe
                        extern "C" fn export_verify(arg0 : * mut u8, arg1 : usize, arg2 :
                        * mut u8, arg3 : usize, arg4 : * mut u8, arg5 : usize,) -> * mut
                        u8 { unsafe { $($path_to_types)*:: _export_verify_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_runt:verifier/verifier#verify")] unsafe extern "C" fn
                        _post_return_verify(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_verify::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub use __export_runt_verifier_verifier_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 16 + 10 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16
                        + 10 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::string::String;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_runt_verifier_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::runt::verifier::verifier::__export_runt_verifier_verifier_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::runt::verifier::verifier);
    };
}
#[doc(inline)]
pub(crate) use __export_runt_verifier_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:runt:verifier:runt-verifier:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 818] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xae\x05\x01A\x02\x01\
A\x06\x01B\x07\x01p}\x01@\x02\x09algorithms\x04data\0\0\0\x04\0\x04hash\x01\x01\x01\
@\x04\x06schemes\x07message\0\x09signature\0\x0apublic-key\0\0\x7f\x04\0\x10veri\
fy-signature\x01\x02\x01@\x02\x05curves\x05pairs\0\0\x7f\x04\0\x0dpairing-check\x01\
\x03\x03\0\x19runt:verifier/host-crypto\x05\0\x01B\x06\x01p}\x01j\x01\0\x01s\x01\
@\x01\x06key-ids\0\x01\x04\0\x14get-verification-key\x01\x02\x01@\x01\x09params-\
ids\0\x01\x04\0\x11get-public-params\x01\x03\x03\0\x1arunt:verifier/host-storage\
\x05\x01\x01B\x0e\x01q\x03\x05valid\0\0\x07invalid\x01s\0\x05error\x01s\0\x04\0\x13\
verification-status\x03\0\0\x01p}\x04\0\x05proof\x03\0\x02\x01p}\x04\0\x0dpublic\
-inputs\x03\0\x04\x01p}\x04\0\x10verification-key\x03\0\x06\x01r\x08\x0dproof-ty\
pe-ids\x07versions\x05curves\x06schemes\x12supports-recursion\x7f\x16trusted-set\
up-required\x7f\x0emax-proof-sizew\x0bdescriptions\x04\0\x11verifier-metadata\x03\
\0\x08\x01@\0\0\x09\x04\0\x08metadata\x01\x0a\x01@\x03\x05proof\x03\x0dpublic-in\
puts\x05\x10verification-key\x07\0\x01\x04\0\x06verify\x01\x0b\x04\0\x16runt:ver\
ifier/verifier\x05\x02\x04\0\x1brunt:verifier/runt-verifier\x04\0\x0b\x13\x01\0\x0d\
runt-verifier\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
